<h1 align = center > Assignment For Numpy </h1>

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
null_vector_1 = np.zeros(10)
null_vector_1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
v1 = np.arange(10, 50)
v1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
np.shape(v1)

(40,)

5. Print the type of the previous array in question 3

In [5]:
type(v1)

numpy.ndarray

6. Print the numpy version and the configuration


**Method 1**

In [6]:
import numpy;
print(numpy.__version__)

1.18.1


**Method 2**

In [7]:
pip show numpy

Name: numpy
Version: 1.18.1
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: c:\programdata\anaconda3\lib\site-packages
Requires: 
Required-by: tables, statsmodels, seaborn, scipy, scikit-learn, PyWavelets, pytest-arraydiff, patsy, pandas, numexpr, numba, mkl-random, mkl-fft, matplotlib, imageio, h5py, Bottleneck, bokeh, bkcharts, astropy
Note: you may need to restart the kernel to use updated packages.


**Method 3**

In [8]:
pip freeze

alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.12
anaconda-project==0.8.3
argh==0.26.2
asn1crypto==1.3.0
astroid==2.3.3
astropy==4.0
atomicwrites==1.3.0
attrs==19.3.0
autopep8==1.4.4
Babel==2.8.0
backcall==0.1.0
backports.functools-lru-cache==1.6.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
bcrypt==3.1.7
beautifulsoup4==4.8.2
bitarray==1.2.1
bkcharts==0.2
bleach==3.1.0
bokeh==1.4.0
boto==2.49.0
Bottleneck==1.3.2
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
Click==7.0
cloudpickle==1.3.0
clyent==1.2.2
colorama==0.4.3
comtypes==1.1.7
conda==4.8.2
conda-build==3.18.11
conda-package-handling==1.6.0
conda-verify==3.4.2
contextlib2==0.6.0.post1
cryptography==2.8
cycler==0.10.0
Cython==0.29.15
cytoolz==0.10.1
dask==2.11.0
decorator==4.4.1
defusedxml==0.6.0
diff-match-patch==20181111
distributed==2.11.0
docutils==0.16
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock==3.0.12
flake8==3.7.9
Flask==1.1.1
fsspec==0.

**Method 4**

In [9]:
pip list

Package                            Version            
---------------------------------- -------------------
alabaster                          0.7.12             
anaconda-client                    1.7.2              
anaconda-navigator                 1.9.12             
anaconda-project                   0.8.3              
argh                               0.26.2             
asn1crypto                         1.3.0              
astroid                            2.3.3              
astropy                            4.0                
atomicwrites                       1.3.0              
attrs                              19.3.0             
autopep8                           1.4.4              
Babel                              2.8.0              
backcall                           0.1.0              
backports.functools-lru-cache      1.6.1              
backports.shutil-get-terminal-size 1.0.0              
backports.tempfile                 1.0                
backports.

**Method 5**

In [10]:
conda list

# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
alabaster                 0.7.12                   py37_0  
anaconda                  2020.02                  py37_0  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.12                   py37_0  
anaconda-project          0.8.4                      py_0  
argh                      0.26.2                   py37_0  
asn1crypto                1.3.0                    py37_0  
astroid                   2.3.3                    py37_0  
astropy                   4.0              py37he774522_0  
atomicwrites              1.3.0                    py37_1  
attrs                     19.3.0                     py_0  
autopep8                  1.4.4                      py_0  
babel                     2.8.0                      py_0  
backcall                  0.1.0     

7. Print the dimension of the array in question 3


### Method 1

In [11]:
print(v1.ndim)

1


### Method 2

In [12]:
print(v1.shape)

(40,)


8. Create a boolean array with all the True values

### 1-D Boolean Array

In [13]:
bool_arr = np.ones(10, dtype=bool)
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

### 2-D Boolean Array

In [14]:
bool_arr = np.ones((3,4), dtype=bool)
bool_arr

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

9. Create a two dimensional array




### Method 1

In [15]:
arr_2d = np.arange(16).reshape(4,4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Method 2

In [16]:
one_d_arr = np.array([1,2,3,4,5,6,11,22,33,44,55,66,111,222,333,444,555,666])
one_d_arr

array([  1,   2,   3,   4,   5,   6,  11,  22,  33,  44,  55,  66, 111,
       222, 333, 444, 555, 666])

In [17]:
two_d_arr = one_d_arr.reshape(3,6)
two_d_arr

array([[  1,   2,   3,   4,   5,   6],
       [ 11,  22,  33,  44,  55,  66],
       [111, 222, 333, 444, 555, 666]])

10. Create a three dimensional array

### Method 1

In [18]:
arr_3d = np.arange(16).reshape(2,2,4)
arr_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

### Method 2

In [19]:
three_d_arr = one_d_arr.reshape(2,3,3)
three_d_arr

array([[[  1,   2,   3],
        [  4,   5,   6],
        [ 11,  22,  33]],

       [[ 44,  55,  66],
        [111, 222, 333],
        [444, 555, 666]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [20]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [22]:
null_vector_2 = np.zeros(10)
null_vector_2[5]=1
null_vector_2

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

### Method 1

In [23]:
identity_matrix = np.identity(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Method 2

In [24]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [25]:
int_arr = np.array([1, 2, 3, 4, 5])
float_arr = int_arr.astype(float)
float_arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


### In this situaton only element-wise-multiplication or mirror-multiplication can be done but dot-multiplication cannot be done.

In [26]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

In [27]:
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [28]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])


In [29]:
new_arr=arr1==arr2
new_arr

array([[False, False, False],
       [False, False, False]])

In [30]:
new_arr=arr1!=arr2
new_arr

array([[ True,  True,  True],
       [ True,  True,  True]])

In [31]:
new_arr=arr1 < arr2
new_arr

array([[False,  True, False],
       [ True, False,  True]])

In [32]:
new_arr=arr1 > arr2
new_arr

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

### Method 1

In [33]:
odd_arr1 = np.arange(1, 10, 2)
odd_arr1

array([1, 3, 5, 7, 9])

### Method 2

In [34]:
odd_arr2 = np.arange(10)
odd_arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
odd_arr2[odd_arr2 % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [36]:
odd_arr1[::] = -1
odd_arr1

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [37]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [38]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [39]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1]= 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [40]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d
arr3d[0,0:2] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [41]:
arr_1d = np.arange(10)
arr_2d = arr_1d.reshape(2,5)
print(arr_2d)
arr_2d[:1,1:]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[1, 2, 3, 4]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [42]:
arr_1d = np.arange(10)
arr_2d = arr_1d.reshape(2,5)
print(arr_2d)
arr_2d[1,1]

[[0 1 2 3 4]
 [5 6 7 8 9]]


6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [43]:
arr_1d = np.arange(10)
arr_2d = arr_1d.reshape(2,5)
print(arr_2d)
arr_2d[:2,2:3]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [44]:
random_arr = np.random.randn(10,10)

In [45]:
print("Minimum Value:")

random_arr.min()

Minimum Value:


-1.9197178584087948

In [46]:
print("Maximum Value:")

random_arr.max()

Maximum Value:


2.0586864514166665

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [47]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [48]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [49]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [50]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [51]:
data

array([[ 2.0551579 ,  0.01708628,  0.22712835, -0.13362499],
       [ 1.16155398,  0.94806557,  0.4902315 ,  0.31567571],
       [-0.11405588,  0.20598985, -0.77648835, -0.78739122],
       [-0.40353291,  1.177623  ,  0.59867237, -0.42082061],
       [ 1.10298427,  1.40724746, -0.27300932, -0.0850575 ],
       [ 1.18937949,  2.36917253,  0.32371805,  1.39436288],
       [-1.73501435,  0.87718185,  0.68756369,  1.03092501]])

In [52]:
data[names != 'Will']

array([[ 2.0551579 ,  0.01708628,  0.22712835, -0.13362499],
       [ 1.16155398,  0.94806557,  0.4902315 ,  0.31567571],
       [-0.40353291,  1.177623  ,  0.59867237, -0.42082061],
       [ 1.18937949,  2.36917253,  0.32371805,  1.39436288],
       [-1.73501435,  0.87718185,  0.68756369,  1.03092501]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [53]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [54]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [55]:
data

array([[-0.01527574, -1.09970204, -0.46814296, -0.61649252],
       [ 0.66298045,  0.02558515,  0.01082483,  0.13752516],
       [-1.43514348,  0.12828557, -0.73962767,  0.1256536 ],
       [ 0.81690506,  0.33975954,  0.49428657, -2.22511981],
       [ 0.07079169, -0.62965287, -2.46143408, -2.35342631],
       [-1.3542729 , -0.01598038,  2.37993581, -0.87163305],
       [-0.77989899,  0.39083292,  1.15076489,  0.03961466]])

In [56]:
data[(names != 'Will') & (names != 'Joe')]

array([[-0.01527574, -1.09970204, -0.46814296, -0.61649252],
       [ 0.81690506,  0.33975954,  0.49428657, -2.22511981]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [57]:
arr = np.arange(1,16)
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [58]:
arr_1d = np.arange(1,17)
arr_2d = arr_1d.reshape(2,2,4)
arr_2d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [59]:
arr_2d.transpose()

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [60]:
arr = np.arange(10)
sqrt_arr = np.sqrt(arr)
sqrt_arr[sqrt_arr < 0.5]=0
sqrt_arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [61]:
a=np.random.rand(12)
b=np.random.rand(12)

In [62]:
a

array([0.96488356, 0.03055821, 0.31936847, 0.90330356, 0.6309972 ,
       0.53708977, 0.74146413, 0.12522863, 0.24300762, 0.86103802,
       0.32298473, 0.90770259])

In [63]:
b

array([0.79697897, 0.73835923, 0.77891342, 0.89654149, 0.8342223 ,
       0.37613501, 0.76478332, 0.51956466, 0.65517108, 0.95581255,
       0.82514714, 0.23462175])

In [64]:
print("Minimum Values between array a & b:")

np.minimum(a, b)

Minimum Values between array a & b:


array([0.79697897, 0.03055821, 0.31936847, 0.89654149, 0.6309972 ,
       0.37613501, 0.74146413, 0.12522863, 0.24300762, 0.86103802,
       0.32298473, 0.23462175])

In [65]:
print("Maximum Values between array a & b:")

np.maximum(a, b)

Maximum Values between array a & b:


array([0.96488356, 0.73835923, 0.77891342, 0.90330356, 0.8342223 ,
       0.53708977, 0.76478332, 0.51956466, 0.65517108, 0.95581255,
       0.82514714, 0.90770259])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [66]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
arr=np.unique(names)
arr=np.sort(arr)
arr

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [67]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
new_arr = np.setdiff1d(a, b)
new_arr

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [68]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [69]:
sampleArray = np.delete(sampleArray , 1, axis = 1) 
sampleArray

array([[34, 73],
       [82, 12],
       [53, 66]])

In [70]:
arr = np.array([[10,10,10]])
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [71]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [72]:
matrix = np.random.randn(20)
matrix

array([-0.24067054, -1.13861407,  0.85967304,  1.6158214 , -0.69248432,
        2.33605684,  1.10665226, -0.09796698, -1.08249797, -1.76355293,
       -1.343468  ,  2.06482696,  0.36339561,  0.88822572,  0.10482219,
       -1.84724275, -1.19493948, -0.04618098, -0.43023984,  0.50352678])

In [73]:
np.cumsum(matrix)

array([-0.24067054, -1.37928461, -0.51961156,  1.09620984,  0.40372552,
        2.73978236,  3.84643462,  3.74846765,  2.66596968,  0.90241674,
       -0.44105125,  1.6237757 ,  1.98717131,  2.87539703,  2.98021922,
        1.13297646, -0.06196302, -0.108144  , -0.53838383, -0.03485705])

<h1 align = center> THE END </h1>