<h1 align = center > Numpy_Assignment_2:: </h1>

In [1]:
import numpy as np

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [3]:
arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(2,5)
arr2 = np.array([10,11, 12, 13, 14, 15, 16, 17, 18, 19]).reshape(2,5)
np.vstack((arr1, arr2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [4]:
arr1 = np.array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1])
arr2 = np.array([5, 6, 7, 8, 9, 1, 1, 1, 1, 1])
np.hstack((arr1, arr2))

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [5]:
arr = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
np.ravel(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [6]:
arr = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [7]:
np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [8]:
arr = np.array(np.random.randn(5, 5) * 10, dtype = np.int)
print(arr)
sqrd_arr = np.square(arr)
sqrd_arr

[[ -9  -5 -14   1  -7]
 [ -4   2  -2  -2  -2]
 [-13  -7 -15  13  21]
 [ -2 -17  -8  -1   0]
 [  3   3 -19 -17   5]]


array([[ 81,  25, 196,   1,  49],
       [ 16,   4,   4,   4,   4],
       [169,  49, 225, 169, 441],
       [  4, 289,  64,   1,   0],
       [  9,   9, 361, 289,  25]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [9]:
arr = np.array(np.random.randn(5, 6) * 10, dtype = np.int)
print(arr)
mean_arr = np.mean(arr)
mean_arr

[[ 12   6  -2   0   3 -18]
 [ 11  16 -19  -3 -17  -2]
 [-12 -11  -6 -16  12  19]
 [  8   9   5 -14   1   8]
 [-16  15 -19 -20  -4  -5]]


-1.9666666666666666

## Question:9

### Find the standard deviation of the previous array in Q8?

In [10]:
np.std(arr)

11.856034562852605

## Question:10

### Find the median of the previous array in Q8?

In [11]:
np.median(arr)

-2.0

## Question:11

### Find the transpose of the previous array in Q8?

In [12]:
arr.transpose()

array([[ 12,  11, -12,   8, -16],
       [  6,  16, -11,   9,  15],
       [ -2, -19,  -6,   5, -19],
       [  0,  -3, -16, -14, -20],
       [  3, -17,  12,   1,  -4],
       [-18,  -2,  19,   8,  -5]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [13]:
arr = np.array(np.random.randn(4, 4) * 10, dtype = np.int)
print(arr)
np.diagonal(arr).sum()

[[  0 -13  -5  -1]
 [-16  11 -11   2]
 [  2 -12   4 -21]
 [  0  15   0  -3]]


12

## Question:13

### Find the determinant of the previous array in Q12?

In [16]:
np.linalg.det(arr)

29718.000000000007

## Question:14

### Find the 5th and 95th percentile of an array?

In [18]:
print("5th percentile is :",np.percentile(arr, 5))
print("95th percentile is :",np.percentile(arr, 95))

5th percentile is : -17.25
95th percentile is : 12.0


## Question:15

### How to find if a given array has any null values?

In [21]:
arr = np.array([1,2,3,4,5,6,7,8,9, np.nan])
array_sum = np.sum(arr)
array_has_nan = np.isnan(array_sum)
array_has_nan

True